
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sistemaVendas?useTimezone=true&serverTimezone=UTC&autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false
        username: root
        password: root
    jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
          ddl-auto: update
        show-sql: false