

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sistemaVendas?useTimezone=true&serverTimezone=UTC&autoReconnect=true&createDatabaseIfNotExist=true&useSSL=false
        username: root
        password: root
    jpa:
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
          ddl-auto: update
        show-sql: false
#config:
#  security:
#    expirationTime: 860_000_000
#    secret: oaudbga8sydu9hijokpláskojiyut6u7i8ok
#    tokenPrefix: Bearer
#    headerString: Authorization